// port-lint: source windows_bindings.rs
package io.github.kotlinmania.ianatimezone

/** Bindings generated by `windows-bindgen` 0.59.0. */
object WindowsBindings {
    object Windows {
        object Globalization {
            class Calendar(private val unknown: WindowsCore.IUnknown) {
                fun clone(): Result<Calendar> = WindowsCore.invokeCalendar(this, "Clone")
                fun setToMin(): Result<Unit> = WindowsCore.invokeUnit(this, "SetToMin")
                fun setToMax(): Result<Unit> = WindowsCore.invokeUnit(this, "SetToMax")
                fun numeralSystem(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "NumeralSystem")
                fun setNumeralSystem(value: WindowsCore.HString): Result<Unit> =
                    WindowsCore.invokeUnit(this, "SetNumeralSystem", value)

                fun getCalendarSystem(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "GetCalendarSystem")

                fun changeCalendarSystem(value: WindowsCore.HString): Result<Unit> =
                    WindowsCore.invokeUnit(this, "ChangeCalendarSystem", value)

                fun getClock(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "GetClock")
                fun changeClock(value: WindowsCore.HString): Result<Unit> =
                    WindowsCore.invokeUnit(this, "ChangeClock", value)

                fun setToNow(): Result<Unit> = WindowsCore.invokeUnit(this, "SetToNow")
                fun firstEra(): Result<Int> = WindowsCore.invokeInt(this, "FirstEra")
                fun lastEra(): Result<Int> = WindowsCore.invokeInt(this, "LastEra")
                fun numberOfEras(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfEras")
                fun era(): Result<Int> = WindowsCore.invokeInt(this, "Era")
                fun setEra(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetEra", value)
                fun addEras(eras: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddEras", eras)
                fun eraAsFullString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "EraAsFullString")

                fun eraAsString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "EraAsString", idealLength)

                fun firstYearInThisEra(): Result<Int> = WindowsCore.invokeInt(this, "FirstYearInThisEra")
                fun lastYearInThisEra(): Result<Int> = WindowsCore.invokeInt(this, "LastYearInThisEra")
                fun numberOfYearsInThisEra(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfYearsInThisEra")
                fun year(): Result<Int> = WindowsCore.invokeInt(this, "Year")
                fun setYear(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetYear", value)
                fun addYears(years: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddYears", years)
                fun yearAsString(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "YearAsString")
                fun yearAsTruncatedString(remainingDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "YearAsTruncatedString", remainingDigits)

                fun yearAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "YearAsPaddedString", minDigits)

                fun firstMonthInThisYear(): Result<Int> = WindowsCore.invokeInt(this, "FirstMonthInThisYear")
                fun lastMonthInThisYear(): Result<Int> = WindowsCore.invokeInt(this, "LastMonthInThisYear")
                fun numberOfMonthsInThisYear(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfMonthsInThisYear")
                fun month(): Result<Int> = WindowsCore.invokeInt(this, "Month")
                fun setMonth(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetMonth", value)
                fun addMonths(months: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddMonths", months)
                fun monthAsFullString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsFullString")

                fun monthAsString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsString", idealLength)

                fun monthAsFullSoloString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsFullSoloString")

                fun monthAsSoloString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsSoloString", idealLength)

                fun monthAsNumericString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsNumericString")

                fun monthAsPaddedNumericString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MonthAsPaddedNumericString", minDigits)

                fun addWeeks(weeks: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddWeeks", weeks)
                fun firstDayInThisMonth(): Result<Int> = WindowsCore.invokeInt(this, "FirstDayInThisMonth")
                fun lastDayInThisMonth(): Result<Int> = WindowsCore.invokeInt(this, "LastDayInThisMonth")
                fun numberOfDaysInThisMonth(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfDaysInThisMonth")
                fun day(): Result<Int> = WindowsCore.invokeInt(this, "Day")
                fun setDay(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetDay", value)
                fun addDays(days: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddDays", days)
                fun dayAsString(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "DayAsString")
                fun dayAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "DayAsPaddedString", minDigits)

                fun dayOfWeekAsFullString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "DayOfWeekAsFullString")

                fun dayOfWeekAsString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "DayOfWeekAsString", idealLength)

                fun dayOfWeekAsFullSoloString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "DayOfWeekAsFullSoloString")

                fun dayOfWeekAsSoloString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "DayOfWeekAsSoloString", idealLength)

                fun firstPeriodInThisDay(): Result<Int> = WindowsCore.invokeInt(this, "FirstPeriodInThisDay")
                fun lastPeriodInThisDay(): Result<Int> = WindowsCore.invokeInt(this, "LastPeriodInThisDay")
                fun numberOfPeriodsInThisDay(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfPeriodsInThisDay")
                fun period(): Result<Int> = WindowsCore.invokeInt(this, "Period")
                fun setPeriod(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetPeriod", value)
                fun addPeriods(periods: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddPeriods", periods)
                fun periodAsFullString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "PeriodAsFullString")

                fun periodAsString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "PeriodAsString", idealLength)

                fun firstHourInThisPeriod(): Result<Int> = WindowsCore.invokeInt(this, "FirstHourInThisPeriod")
                fun lastHourInThisPeriod(): Result<Int> = WindowsCore.invokeInt(this, "LastHourInThisPeriod")
                fun numberOfHoursInThisPeriod(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfHoursInThisPeriod")
                fun hour(): Result<Int> = WindowsCore.invokeInt(this, "Hour")
                fun setHour(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetHour", value)
                fun addHours(hours: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddHours", hours)
                fun hourAsString(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "HourAsString")
                fun hourAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "HourAsPaddedString", minDigits)

                fun minute(): Result<Int> = WindowsCore.invokeInt(this, "Minute")
                fun setMinute(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetMinute", value)
                fun addMinutes(minutes: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddMinutes", minutes)
                fun minuteAsString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MinuteAsString")

                fun minuteAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "MinuteAsPaddedString", minDigits)

                fun second(): Result<Int> = WindowsCore.invokeInt(this, "Second")
                fun setSecond(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetSecond", value)
                fun addSeconds(seconds: Int): Result<Unit> = WindowsCore.invokeUnit(this, "AddSeconds", seconds)
                fun secondAsString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "SecondAsString")

                fun secondAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "SecondAsPaddedString", minDigits)

                fun nanosecond(): Result<Int> = WindowsCore.invokeInt(this, "Nanosecond")
                fun setNanosecond(value: Int): Result<Unit> = WindowsCore.invokeUnit(this, "SetNanosecond", value)
                fun addNanoseconds(nanoseconds: Int): Result<Unit> =
                    WindowsCore.invokeUnit(this, "AddNanoseconds", nanoseconds)

                fun nanosecondAsString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "NanosecondAsString")

                fun nanosecondAsPaddedString(minDigits: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "NanosecondAsPaddedString", minDigits)

                fun compare(other: Calendar): Result<Int> = WindowsCore.invokeInt(this, "Compare", other)
                fun copyTo(other: Calendar): Result<Unit> = WindowsCore.invokeUnit(this, "CopyTo", other)
                fun firstMinuteInThisHour(): Result<Int> = WindowsCore.invokeInt(this, "FirstMinuteInThisHour")
                fun lastMinuteInThisHour(): Result<Int> = WindowsCore.invokeInt(this, "LastMinuteInThisHour")
                fun numberOfMinutesInThisHour(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfMinutesInThisHour")
                fun firstSecondInThisMinute(): Result<Int> = WindowsCore.invokeInt(this, "FirstSecondInThisMinute")
                fun lastSecondInThisMinute(): Result<Int> = WindowsCore.invokeInt(this, "LastSecondInThisMinute")
                fun numberOfSecondsInThisMinute(): Result<Int> = WindowsCore.invokeInt(this, "NumberOfSecondsInThisMinute")
                fun resolvedLanguage(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "ResolvedLanguage")

                fun isDaylightSavingTime(): Result<Boolean> = WindowsCore.invokeBoolean(this, "IsDaylightSavingTime")
                fun getTimeZone(): Result<WindowsCore.HString> = WindowsCore.invokeHString(this, "GetTimeZone")
                fun changeTimeZone(timezoneId: WindowsCore.HString): Result<Unit> =
                    WindowsCore.invokeUnit(this, "ChangeTimeZone", timezoneId)

                fun timeZoneAsFullString(): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "TimeZoneAsFullString")

                fun timeZoneAsString(idealLength: Int): Result<WindowsCore.HString> =
                    WindowsCore.invokeHString(this, "TimeZoneAsString", idealLength)

                companion object {
                    fun new(): Result<Calendar> =
                        WindowsCore.activationFactory("Windows.Globalization.Calendar")
                            .map { Calendar(it.activateInstance()) }

                    private fun iActivationFactory(callback: (WindowsCore.GenericFactory) -> Result<Any?>): Result<Any?> =
                        callback(WindowsCore.genericFactory("Windows.Globalization.Calendar"))

                    private fun iCalendarFactory(callback: (ICalendarFactory) -> Result<Any?>): Result<Any?> =
                        callback(ICalendarFactory)

                    private fun iCalendarFactory2(callback: (ICalendarFactory2) -> Result<Any?>): Result<Any?> =
                        callback(ICalendarFactory2)
                }
            }

            object ICalendar
            object ICalendarFactory
            object ICalendarFactory2
            object ITimeZoneOnCalendar

            data class ICalendarVtbl(
                val clone: String = "Clone",
                val setToMin: String = "SetToMin",
                val setToMax: String = "SetToMax",
                val numeralSystem: String = "NumeralSystem",
                val setNumeralSystem: String = "SetNumeralSystem",
                val getCalendarSystem: String = "GetCalendarSystem",
                val changeCalendarSystem: String = "ChangeCalendarSystem",
                val getClock: String = "GetClock",
                val changeClock: String = "ChangeClock",
                val setToNow: String = "SetToNow",
                val firstEra: String = "FirstEra",
                val lastEra: String = "LastEra",
                val numberOfEras: String = "NumberOfEras",
                val era: String = "Era",
                val setEra: String = "SetEra",
                val addEras: String = "AddEras",
                val eraAsFullString: String = "EraAsFullString",
                val eraAsString: String = "EraAsString",
                val firstYearInThisEra: String = "FirstYearInThisEra",
                val lastYearInThisEra: String = "LastYearInThisEra",
                val numberOfYearsInThisEra: String = "NumberOfYearsInThisEra",
                val year: String = "Year",
                val setYear: String = "SetYear",
                val addYears: String = "AddYears",
                val yearAsString: String = "YearAsString",
                val yearAsTruncatedString: String = "YearAsTruncatedString",
                val yearAsPaddedString: String = "YearAsPaddedString",
                val firstMonthInThisYear: String = "FirstMonthInThisYear",
                val lastMonthInThisYear: String = "LastMonthInThisYear",
                val numberOfMonthsInThisYear: String = "NumberOfMonthsInThisYear",
                val month: String = "Month",
                val setMonth: String = "SetMonth",
                val addMonths: String = "AddMonths",
                val monthAsFullString: String = "MonthAsFullString",
                val monthAsString: String = "MonthAsString",
                val monthAsFullSoloString: String = "MonthAsFullSoloString",
                val monthAsSoloString: String = "MonthAsSoloString",
                val monthAsNumericString: String = "MonthAsNumericString",
                val monthAsPaddedNumericString: String = "MonthAsPaddedNumericString",
                val addWeeks: String = "AddWeeks",
                val firstDayInThisMonth: String = "FirstDayInThisMonth",
                val lastDayInThisMonth: String = "LastDayInThisMonth",
                val numberOfDaysInThisMonth: String = "NumberOfDaysInThisMonth",
                val day: String = "Day",
                val setDay: String = "SetDay",
                val addDays: String = "AddDays",
                val dayAsString: String = "DayAsString",
                val dayAsPaddedString: String = "DayAsPaddedString",
                val dayOfWeekAsFullString: String = "DayOfWeekAsFullString",
                val dayOfWeekAsString: String = "DayOfWeekAsString",
                val dayOfWeekAsFullSoloString: String = "DayOfWeekAsFullSoloString",
                val dayOfWeekAsSoloString: String = "DayOfWeekAsSoloString",
                val firstPeriodInThisDay: String = "FirstPeriodInThisDay",
                val lastPeriodInThisDay: String = "LastPeriodInThisDay",
                val numberOfPeriodsInThisDay: String = "NumberOfPeriodsInThisDay",
                val period: String = "Period",
                val setPeriod: String = "SetPeriod",
                val addPeriods: String = "AddPeriods",
                val periodAsFullString: String = "PeriodAsFullString",
                val periodAsString: String = "PeriodAsString",
                val firstHourInThisPeriod: String = "FirstHourInThisPeriod",
                val lastHourInThisPeriod: String = "LastHourInThisPeriod",
                val numberOfHoursInThisPeriod: String = "NumberOfHoursInThisPeriod",
                val hour: String = "Hour",
                val setHour: String = "SetHour",
                val addHours: String = "AddHours",
                val hourAsString: String = "HourAsString",
                val hourAsPaddedString: String = "HourAsPaddedString",
                val minute: String = "Minute",
                val setMinute: String = "SetMinute",
                val addMinutes: String = "AddMinutes",
                val minuteAsString: String = "MinuteAsString",
                val minuteAsPaddedString: String = "MinuteAsPaddedString",
                val second: String = "Second",
                val setSecond: String = "SetSecond",
                val addSeconds: String = "AddSeconds",
                val secondAsString: String = "SecondAsString",
                val secondAsPaddedString: String = "SecondAsPaddedString",
                val nanosecond: String = "Nanosecond",
                val setNanosecond: String = "SetNanosecond",
                val addNanoseconds: String = "AddNanoseconds",
                val nanosecondAsString: String = "NanosecondAsString",
                val nanosecondAsPaddedString: String = "NanosecondAsPaddedString",
                val compare: String = "Compare",
                val copyTo: String = "CopyTo",
                val firstMinuteInThisHour: String = "FirstMinuteInThisHour",
                val lastMinuteInThisHour: String = "LastMinuteInThisHour",
                val numberOfMinutesInThisHour: String = "NumberOfMinutesInThisHour",
                val firstSecondInThisMinute: String = "FirstSecondInThisMinute",
                val lastSecondInThisMinute: String = "LastSecondInThisMinute",
                val numberOfSecondsInThisMinute: String = "NumberOfSecondsInThisMinute",
                val resolvedLanguage: String = "ResolvedLanguage",
                val isDaylightSavingTime: String = "IsDaylightSavingTime",
            )

            data class ICalendarFactoryVtbl(
                val createCalendarDefaultCalendarAndClock: String = "CreateCalendarDefaultCalendarAndClock",
                val createCalendar: String = "CreateCalendar",
            )

            data class ICalendarFactory2Vtbl(
                val createCalendarWithTimeZone: String = "CreateCalendarWithTimeZone",
            )

            data class ITimeZoneOnCalendarVtbl(
                val getTimeZone: String = "GetTimeZone",
                val changeTimeZone: String = "ChangeTimeZone",
                val timeZoneAsFullString: String = "TimeZoneAsFullString",
                val timeZoneAsString: String = "TimeZoneAsString",
            )
        }
    }
}

object WindowsCore {
    class IUnknown
    class IInspectable : IUnknown()
    data class HString(private val value: String) {
        override fun toString(): String = value
    }

    data class GenericFactory(private val runtimeName: String) {
        fun activateInstance(): IUnknown = IUnknown()
    }

    fun activationFactory(runtimeName: String): Result<GenericFactory> = Result.success(GenericFactory(runtimeName))
    fun genericFactory(runtimeName: String): GenericFactory = GenericFactory(runtimeName)

    fun invokeCalendar(target: Any, name: String): Result<WindowsBindings.Windows.Globalization.Calendar> =
        Result.success(WindowsBindings.Windows.Globalization.Calendar(IUnknown()))

    fun invokeUnit(target: Any, name: String, vararg args: Any?): Result<Unit> = Result.success(Unit)
    fun invokeInt(target: Any, name: String, vararg args: Any?): Result<Int> = Result.success(0)
    fun invokeBoolean(target: Any, name: String, vararg args: Any?): Result<Boolean> = Result.success(false)
    fun invokeHString(target: Any, name: String, vararg args: Any?): Result<HString> = Result.success(HString(""))
}
